version: '3'

services:
  mongodb:
    image: mongo
    container_name: hl7-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  common:
    build:
      context: ./common
      args:
        username: ${USER}
    image: ${USER}/hl7-common
    depends_on:
      - mongodb
    command: /bin/bash -c "echo 'common' services"

  auth:
    build:
      context: ./auth
      args:
        username: ${USER}
    image: ${USER}/hl7-auth
    ports:
      - "8090:8090"
    depends_on:
      - common
    working_dir: /root/hl7-auth/auth
    command: mvn spring-boot:run -Dspring-boot.run.arguments=--db.host=mongodb

  tcamt:
    build:
      context: ./tcamt
      args:
        username: ${USER}
    image: ${USER}/hl7-tcamt
    depends_on:
      - auth
    working_dir: /root/tcamt-2/webapp
    command: |
        /bin/bash -c "
            mvn test -Dspring.data.mongodb.host=mongodb
            mvn spring-boot:run -Dspring-boot.run.arguments=\"--spring.data.mongodb.host=mongodb --auth.url=http://auth:8090\" || exit 0
        "
  dev:
    build:
      context: ./dev
      args:
        username: ${USER}
    image: ${USER}/hl7-dev
    depends_on:
      - auth
    volumes:
      - home:/home/${USER}
      - ${HOME}:/mnt
    user: ${USER}
    entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
    command: |
        /bin/bash -c "
            sudo /root/setup.sh
            /bin/bash || exit 0
        "
volumes:
  mongodb: {}
  home: {}
